store:
    resource: "@AppBundle/Resources/config/routing/store.yml"
    host:     "{country}.store.local"    
    prefix:   /
    
login_route:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check
    
logout:
    path: /logout    