services:
    app.country:
        class: AppBundle\Service\CountryService
        arguments: [@twig]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }